/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wrorobot-model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot(props) {
  const { nodes, materials } = useGLTF('models/wrorobot-model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.robotv7_1.geometry} material={materials['Plastic_-_Translucent_Glossy_(Red)']} />
      <mesh geometry={nodes.robotv7_2.geometry} material={materials['Display_-_7_Segments_-_LED']} />
      <mesh geometry={nodes.robotv7_3.geometry} material={materials['ABS_(White)_(1)']} />
      <mesh geometry={nodes.robotv7_4.geometry} material={materials['ABS_(White)']} />
      <mesh geometry={nodes.robotv7_5.geometry} material={materials['ABS_(lightgray)']} />
      <mesh geometry={nodes.robotv7_6.geometry} material={materials['ABS_(lightgray)']} />
      <mesh geometry={nodes.robotv7_7.geometry} material={materials['ABS_(White)_(1)_1']} />
      <mesh geometry={nodes.robotv7_8.geometry} material={materials['Rubber_-_Soft']} />
      <mesh geometry={nodes.robotv7_9.geometry} material={materials['Opaque(53,53,53)']} />
      <mesh geometry={nodes.robotv7_10.geometry} material={materials['ABS_(darkgray)_(1)_(1)']} />
      <mesh geometry={nodes.robotv7_11.geometry} material={materials['Opaque(63,63,63)']} />
      <mesh geometry={nodes.robotv7_12.geometry} material={materials['ABS_(darkgray)']} />
      <mesh geometry={nodes.robotv7_13.geometry} material={materials['ABS_(darkgray)_(1)_(2)']} />
      <mesh geometry={nodes.robotv7_14.geometry} material={materials['Opaque(163,169,170)']} />
      <mesh geometry={nodes.robotv7_15.geometry} material={materials['Opaque(73,73,73)']} />
      <mesh geometry={nodes.robotv7_16.geometry} material={materials['Opaque(165,159,143)']} />
      <mesh geometry={nodes.robotv7_17.geometry} material={materials['Opaque(217,196,147)']} />
      <mesh geometry={nodes.robotv7_18.geometry} material={materials['Opaque(229,202,158)']} />
      <mesh geometry={nodes.robotv7_19.geometry} material={materials['Opaque(192,192,192)']} />
      <mesh geometry={nodes.robotv7_20.geometry} material={materials['Opaque(255,255,128)']} />
      <mesh geometry={nodes.robotv7_21.geometry} material={materials['Opaque(208,208,208)']} />
      <mesh geometry={nodes.robotv7_22.geometry} material={materials['Opaque(232,173,35)']} />
      <mesh geometry={nodes.robotv7_23.geometry} material={materials['Opaque(40,40,40)']} />
      <mesh geometry={nodes.robotv7_24.geometry} material={materials['Opaque(64,64,64)']} />
      <mesh geometry={nodes.robotv7_25.geometry} material={materials['Opaque(25,25,25)']} />
      <mesh geometry={nodes.robotv7_26.geometry} material={materials['Opaque(196,197,196)']} />
      <mesh geometry={nodes.robotv7_27.geometry} material={materials['Opaque(203,203,203)']} />
      <mesh geometry={nodes.robotv7_28.geometry} material={materials['Opaque(255,255,255)']} />
      <mesh geometry={nodes.robotv7_29.geometry} material={materials['Opaque(204,207,204)']} />
      <mesh geometry={nodes.robotv7_30.geometry} material={materials['Opaque(26,26,26)']} />
      <mesh geometry={nodes.robotv7_31.geometry} material={materials['Opaque(127,127,127)']} />
      <mesh geometry={nodes.robotv7_32.geometry} material={materials['Opaque(160,160,160)']} />
      <mesh geometry={nodes.robotv7_33.geometry} material={materials['Opaque(245,245,246)']} />
      <mesh geometry={nodes.robotv7_34.geometry} material={materials['Opaque(244,229,167)']} />
      <mesh geometry={nodes.robotv7_35.geometry} material={materials['Opaque(45,45,45)']} />
      <mesh geometry={nodes.robotv7_36.geometry} material={materials['Opaque(255,207,128)']} />
      <mesh geometry={nodes.robotv7_37.geometry} material={materials['Opaque(230,230,230)']} />
      <mesh geometry={nodes.robotv7_38.geometry} material={materials['Opaque(77,77,77)']} />
      <mesh geometry={nodes.robotv7_39.geometry} material={materials['Opaque(0,127,0)']} />
      <mesh geometry={nodes.robotv7_40.geometry} material={materials['Opaque(255,191,0)']} />
      <mesh geometry={nodes.robotv7_41.geometry} material={materials['Opaque(123,97,74)']} />
      <mesh geometry={nodes.robotv7_42.geometry} material={materials['Opaque(211,212,213)']} />
      <mesh geometry={nodes.robotv7_43.geometry} material={materials['Opaque(30,30,30)']} />
      <mesh geometry={nodes.robotv7_44.geometry} material={materials['Opaque(242,236,238)']} />
      <mesh geometry={nodes.robotv7_45.geometry} material={materials['Opaque(160,165,169)']} />
      <mesh geometry={nodes.robotv7_46.geometry} material={materials['Opaque(205,183,57)']} />
      <mesh geometry={nodes.robotv7_47.geometry} material={materials['Opaque(201,26,9)']} />
      <mesh geometry={nodes.robotv7_48.geometry} material={materials['Opaque(178,178,178)']} />
      <mesh geometry={nodes.robotv7_49.geometry} material={materials['Opaque(0,132,229)']} />
      <mesh geometry={nodes.robotv7_50.geometry} material={materials['Opaque(0,132,229)_(1)']} />
      <mesh geometry={nodes.robotv7_51.geometry} material={materials['Opaque(8,229,0)']} />
      <mesh geometry={nodes.robotv7_52.geometry} material={materials['Opaque(229,234,237)']} />
      <mesh geometry={nodes.robotv7_53.geometry} material={materials['Opaque(198,193,188)']} />
      <mesh geometry={nodes.robotv7_54.geometry} material={materials['ABS_(White)_(2)']} />
      <mesh geometry={nodes.robotv7_55.geometry} material={materials['Opaque(152,170,175)']} />
      <mesh geometry={nodes.robotv7_56.geometry} material={materials['Opaque(179,179,179)']} />
      <mesh geometry={nodes.robotv7_57.geometry} material={materials['Opaque(246,246,243)']} />
      <mesh geometry={nodes.robotv7_58.geometry} material={materials['Opaque(237,206,195)']} />
      <mesh geometry={nodes.robotv7_59.geometry} material={materials['Opaque(255,145,42)']} />
      <mesh geometry={nodes.robotv7_60.geometry} material={materials.tan} />
      <mesh geometry={nodes.robotv7_61.geometry} material={materials['ABS_(darkgray)_(1)']} />
    </group>
  )
}

useGLTF.preload('models/wrorobot-model.glb')
